name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare library
      run: |
        mkdir temp
        git clone --depth 1 -b master https://github.com/axiomatic-systems/Bento4
        cp -r src/. temp
        cp -r Bento4/Source/C++/Core/. src
        cp -r Bento4/Source/C++/Codecs/. src
        cp -r Bento4/Source/C++/Crypto/. src
        cp -r Bento4/Source/C++/MetaData/. src
        cp -r temp/. src

    - name: Build library
      run: |
        cmake -B build -D CMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Run application
      working-directory: ${{ github.workspace}}/build
      run: ./Ap4Decrypt
