name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    
    - name: Prepare library
      run: |
        mkdir temp
        git clone https://github.com/axiomatic-systems/Bento4
        git checkout 0010f4fd420ef7d6504d2e401a46c15f4ef3d3ca
        cp -r src/. temp
        cp -r Bento4/Source/C++/Core/. src
        cp -r Bento4/Source/C++/Codecs/. src
        cp -r Bento4/Source/C++/Crypto/. src
        cp -r Bento4/Source/C++/MetaData/. src
        cp -r temp/. src

    - name: Build library
      run: |
        cmake -B build -D CMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Run application
      working-directory: ${{ github.workspace}}/build
      run: ./Ap4Decrypt ${{ secrets.KEYID }} ${{ secrets.KEY }} ${{ github.workspace }}/media/video-init.mp4 ${{ github.workspace }}/media/video-40.mp4

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: Mediafile.zip
        path: ${{ github.workspace}}/build/out.mp4
        if-no-files-found: error
        retention-days: 1
