name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Prepare library
      shell: cmd
      run: |
        mkdir temp
        git clone --depth 1 -b master https://github.com/axiomatic-systems/Bento4
        copy src\* temp
        copy /y /v "Bento4\Source\C++\Core\*" src
        copy /y /v "Bento4\Source\C++\Codecs\*" src
        copy /y /v "Bento4\Source\C++\Crypto\*" src
        copy /y /v "Bento4\Source\C++\MetaData\*" src
        copy /y /v temp\* src
        
    - name: Build library
      shell: cmd
      run: |
        cmake -B build
        cmake --build build --config Release
        
    - name: Run application
      shell: cmd
      working-directory: ${{ github.workspace}}\build\Release
      run: Ap4Decrypt.exe
